trigger:
  - main
pr:
  - main

jobs:
  - job: Build_And_Test
    pool:
      name: $(pool)

    strategy:
      matrix:
        "Linux - Node 16.x":
          pool: azsdk-pool-mms-ubuntu-2004-general
          nodeVersion: "16.x"

        "Windows - Node 16.x":
          pool: azsdk-pool-mms-win-2019-general
          nodeVersion: "16.x"

        "Linux - Node 18.x":
          pool: azsdk-pool-mms-win-2019-general
          nodeVersion: "18.x"

        "Windows - Node 18.x":
          pool: azsdk-pool-mms-win-2019-general
          nodeVersion: "18.x"

    steps:
      - script: echo '##vso[task.setvariable variable=CADL_VS_CI_BUILD;]true'
        displayName: Enable official Visual Studio extension build
        condition: eq(variables['Agent.OS'], 'Windows_NT')

      - template: pull-request-common.yml
        parameters:
          nodeVersion: $(nodeVersion)
          poolName: $(pool)

  - job: docker_build
    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
    steps:
      - script: docker build -f ./docker/Dockerfile .
        displayName: Docker build

  - job: Consistency_Check
    pool:
      name: azsdk-pool-mms-ubuntu-2004-general

    steps:
      - template: pull-request-consistency.yml
